name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push --force https://hwanginseo04:$HF_TOKEN@huggingface.co/spaces/hwanginseo04/my-hfhf-app main
          